### ISSUE TITLE
Unity 5.3.4f1 - TuneAndroid Fails to Initialize

### ISSUE THREAD

**Issue by PetroUnityDev** [MobileAppTracking/unity-plugin#5]
The com.tune.Tune.getInstance method on the Java side always returns null until the init method is called. This causes the constructor of the TuneAndroid class on the Unity C# side to throw an exception as the AndroidJavaObject is being constructed with a null pointer (see attached Android logcat excerpt) and the call to the TuneAndroid Init method goes through instance retrieval/TuneAndroid construction first, causing it to fail.

Removing line 23 from the TuneAndroid.cs solves the problem:

This:

        private TuneAndroid()
        {
            ajcInstance = ajcTune.CallStatic<AndroidJavaObject>("getInstance");
            ajcCurrentActivity = ajcUnityPlayer.GetStatic<AndroidJavaObject>("currentActivity");
        }

Becomes:

        private TuneAndroid()
        {
            ajcCurrentActivity = ajcUnityPlayer.GetStatic<AndroidJavaObject>("currentActivity");
        }

This works as the Init method on the Unity C# side assigns the ajcInstance reference using the returned value from calling the init method on the Java side, which is the Tune instance.

[TuneSDK_TuneAndroid_Constructor_Failure.txt](https://github.com/MobileAppTracking/unity-plugin/files/221865/TuneSDK_TuneAndroid_Constructor_Failure.txt)

**Comment by john-gu** [comment]
Thanks, we've removed the null getInstance call. Our 4.0 plugin now supports initializing from both native and Unity, so this change grabs any existing instance from a call to `init` instead of `getInstance`:
https://github.com/MobileAppTracking/unity-plugin/commit/62bf008d20f716b40daee3e85f88075648fc4655#diff-47121912ff80f68559a9f600e44dfccfR44

We've released a 4.0.1 hotfix to address this:
https://github.com/MobileAppTracking/unity-plugin/releases/tag/v4.0.1
